/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppColor: typeof import('./src/views/common/AppColor.vue')['default']
    AppErrorList: typeof import('./src/views/common/AppErrorList.vue')['default']
    AppList: typeof import('./src/views/common/AppList.vue')['default']
    AppSoundPlayer: typeof import('./src/views/common/AppSoundPlayer.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroupText']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTh: typeof import('bootstrap-vue-next/components/BTable')['BTh']
    BThead: typeof import('bootstrap-vue-next/components/BTable')['BThead']
    BTr: typeof import('bootstrap-vue-next/components/BTable')['BTr']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VueFeather: typeof import('vue-feather')['default']
  }
  export interface GlobalDirectives {
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
