version: "3.9"
services:
  rfidsecuritysvc:
    depends_on:
      - magicband-reader
    image: "rfid-security-svc:latest"
    volumes:
      - type: bind
        source: ../rfid-security-svc/
        target: /rfid-security-svc
      - rfid-db:/rfid-db
  rfidsecurityui:
    build:
      context: ../rfid-security-ui
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    depends_on:
      - rfidsecuritysvc
    environment:
      WEBPACK_PUBLIC: "devpi.local:8080"
      WEBPACK_DISABLE_HOST_CHECK: "true"
    image: rfid-security-ui:latest
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ../rfid-security-ui/
        target: /rfid-security-ui
  magicband-reader:
    image: "mock-magicband-reader:production"
volumes:
  rfid-db:
    external: true
